apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-serviceaccount
  namespace: default
secrets:
- name: webapp-serviceaccount-token
---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeU1ETXhOekF5TWpZek5Wb1hEVE15TURNeE5UQXlNall6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEw2ClNwQnFHTVFGVG9VSkI5dzNhTlNSNDcyYjRxckFWSEpOTitTeXgxRmF2WTZReXNLOFFoOUJrWTVCT3R2SEhnVnoKL1E5bXJPUktFSjMyN3cwSDF5Q3VKcGRCWHF2Z2EvdHZsY2lZeWxRRS8rbDFnUUxOcnVKaVJENXR3azFHR0d0MApOaC9rSFNNVFVIOGQ2Q2dmSklFUkt5bmNaMlF5RVpSV1REL08xVUNhWUFiTWxYdXVNZytvdlJWVHZRTDFaU1NaCkhQbVpmSFBXeXY0TUp3Qk1IVXFkVWtUMHprQ3pIR3hpY3FMU1R5NzdTaERyZUgrektFTTZDT0x4MFpaQlp2NVgKR0R4MTNYblhON1VGMjA2aldwY28rRFArcmZwUFNqRERWeko3ZTJ0aDVGcTVYWkk1UUlQWnI1K0lZWEdWaTBEUQpSUDhCVUZDK0VYaEwvR0NBcTY4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSTzJSdzhYdjUzMWJudnduYURrd1FZdjMwZjhqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFUSzhmMW5wdAo1STRTNDJuMUxFZ0JhUytRdjA2bE5VRnlZYUsvWnFNeWsyeGRZSjNNd0ZuWjB6b25kQ1R6QW1oeWNEbnQzbmZQCk1tbXMzVzBoRkR1cXFmNy9QeW96QW5qaHVvQSsrVG9MSmhiMS9NeGw2Q1pWM2NzY25PZG44WkR1MVVRMnRPdXoKSWRoaUJEa1pZVzhWTkh6VGN0NGc4bzE1UnNKd0NaSXluWG1yTjJVb0RrNGxYdk16Q0hjZGVEem9yREpNTUd6OQovQlhWTys2NTFyTkV6dytIWG1HanB0MldnbjV0S1VqVXdod0t6cTBFNTZYandYakY4d1VKdmFMSkxvQi9XdlRkCmU0L0IrZXE2MVN0S0dUcXBpNk9aZ1RmSEdvcktFMzViK3Q0ZFNZUjdTQ0h1dFMxUHRGaURIbDdRYmFGQ3lQa3EKQkpURm5BMURONGRaNWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: ZGVmYXVsdA==
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrb3pjRnA2UmxwcVpsWkZWRkUyV21GWlVtWm5hVUpwYlhGR2JtbGhTSGxQYmpaYVFXdHZXbk5TVWswaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbmRsWW1Gd2NDMXpaWEoyYVdObFlXTmpiM1Z1ZEMxMGIydGxiaTFtY3pkdGJDSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSjNaV0poY0hBdGMyVnlkbWxqWldGalkyOTFiblFpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUl5WW1RMlltSXpZeTA1WldWaUxUUXpZakF0WWpGaVppMWtZMlJrTkdGaE16azNOek1pTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNlpHVm1ZWFZzZERwM1pXSmhjSEF0YzJWeWRtbGpaV0ZqWTI5MWJuUWlmUS5VR3JTQ0RtWG1DWDlQQzFIU2hFV1ViamhwYkxLVVkxYjV2UnUxbExiMDBHTWU2VC1LRWdNQy15dkpWLXgzM0NBeHFhRlBYaUJVaHFrSkJ4S2hEdDFfTjBKSFlDNEM2a3ByQ241ZWNFYS1CZndOVzJJX0JQSXJFMFNEQ3VCb2FlMFZUZE1haURFOGhqakhfWm4yeVdqZkVPempwejhkdldUYS1ROHI5LTI1MTZwTGhvaVBvQ0J1OVNnZlUzajlGTy1DVDlVeUh4NFFwelVoU0JKM0JOZldEWjBNa0l4SmNzTndGSGhtay1CWjAwbGVvMVJ3UGtzaEt6WEo0N19zTkk5bGVFbkpWUXh2X1RpR1dkSGZYZkF1OElzRXRzU3VELWJ0aFZmLTN2Mkh1TjZxMFhUU0swU1QweEJtRnFPOGkxNE1oTjZMLUt1NnJMOGdIVGdqMkpPYkE=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: webapp-serviceaccount
    kubernetes.io/service-account.uid: 2bd6bb3c-9eeb-43b0-b1bf-dcdd4aa39773
  creationTimestamp: "2022-09-22T23:48:59Z"
  name: webapp-serviceaccount-token
  namespace: default
  resourceVersion: "2777"
  uid: ee95631c-5470-452e-b6a8-6f0e924206b1
type: kubernetes.io/service-account-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'webapp'
        vault.hashicorp.com/agent-inject-secret-config: 'secret/webapp/config'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/webapp/config" -}}
              {{ range $Key, $Value := .Data.data }}
                export {{$Key}}="{{$Value}}"
              {{ end }}
          {{- end }}
    spec:
      serviceAccountName: vault
      containers:
        - name: app
         # args: [ "source /vault/secrets/config && bash" ]
          image: burtlo/exampleapp-ruby:k8s
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              value: 'http://vault:8200'
            - name: JWT_PATH
              value: '/var/run/secrets/kubernetes.io/serviceaccount/token'
            - name: SERVICE_PORT
              value: '8080'