version: "3.8"
services:
  vault:
    image: vault:1.11.3
    volumes:
      - ${PWD}/vault/config/server:/vault/config/server
      - ${PWD}/vault/data:/vault/data
    command: "vault server -config=/vault/config/server/server-config.hcl"
    container_name: vault
    cap_add:
      - IPC_LOCK #vault needs to lock memory
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
  vault-agent:
    image: vault:1.11.3
    volumes:
      - ${PWD}/vault/config/agent:/vault/config/agent
      - ${PWD}/vault/data:/vault/data
    command: "vault agent -config=/vault/config/agent/agent-config.hcl"
    container_name: vault-agent
    cap_add:
      - IPC_LOCK #vault needs to lock memory
    environment:
      - VAULT_ADDR=http://vault:8200
  catalog-api:
    depends_on:
      - mongodb
    image: patrickreinan/commerce-catalogapi:latest
    container_name: catalogapi
    ports:
    - 8080:80
    environment:
      - CATALOG__VERSION=1
    env_file:
      - ./vault/data/vars.env
    volumes:
      - ${PWD}/vault/data:/vault/data
  mongodb:
    image: mongo
    container_name: mongo
networks:
  default:
     
     


    